server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      INDENT_OUTPUT: true
  datasource:
    url: ${maven.db.url}
    username: ${maven.db.username}
    password: ${maven.db.password}
    driver-class-name: ${maven.db.driver}
  redis:
    host: ${maven.redis.host}
    password: ${maven.redis.password}
    port: ${maven.redis.port}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: com.jldata.smartframe.core.common.MySQL5DialectUTF8
    database: mysql

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800

logging:
  level:
    root: warn
    org.springframework.web: debug
    org.hibernate: error