server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      INDENT_OUTPUT: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: db_test
    password: db_test
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 47.75.36.103
    password: 123456
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: com.jldata.smartframe.core.common.MySQL5DialectUTF8
    database: mysql


jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800